# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallShieldInstall@1
  inputs:
    ISVersion: '2021'
    LicType: 'cls'
    ISLicenseCLS: '6F5XTE6YRV7U'


- task: InstallShieldBuild@1
  inputs:
    PrjName: 'COM EXTRACTION/BMSI_Comp_ComExtract64Bit_BVT/BMSI_Comp_ComExtract64Bit_BVT.ism'
    Parameters: 
    AgentLoc: 'HostedAgent'
    LicType: 'cls'
    ISLicenseCLS: '6F5XTE6YRV7U'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'