# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallShieldBuild@1
  inputs:
  PrjName: '2021/Setup1/Setup1.sln'
  AgentLoc: 'HostedAgent'
  LicType: 'cls'
  ISLicenseCLS: '6F5XTE6YRV7U'
