# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
name: Default
vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: InstallShieldBuild@1
  inputs:
    Prjname: 'MyProjectName-1.ism'
    Parameters: '-r "Release 1" -y "2.2.1"'
    AgentLoc: 'PrivateAgent'
    SABPath: 'C:\Program Files (x86)\InstallShield\2020'


- task: InstallShieldBuild@1
  inputs:
    Prjname: 'My Project Name-1.ism'
    Parameters: '-r "Release 2" -y "2.2.3"'
    AgentLoc: 'PrivateAgent'
    SABPath: 'C:\Program Files (x86)\InstallShield\2020'


