# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: InstallShieldBuild@1
  inputs:
    Prjname: 'My Project Name-1.ism'
    AgentLoc: 'HostedAgent'
    ServerPort: 'ec2-3-15-222-195.us-east-2.compute.amazonaws.com:27000'